services:
  api:
    image: fastapi-fileserver
    build:
      context: .
    env_file:
      - .env
    ports:
      - 5001:5001
    networks:
      - app_network
    volumes:
      - D:/uploaded_files:/file_server/app/uploaded_files


#  db:
#    image: postgres:15.6-bullseye
#    hostname: postgres
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_TEST_DB: ${TEST_DB_NAME}
#    volumes:
#      - api-db-data:/var/lib/postgresql/data
#      - ./docker_support/create-test-db.sh:/docker-entrypoint-initdb.d/create-test-db.sh
#    ports:
#      - ${DB_PORT}:${DB_PORT}
#    networks:
#      - api-network
#    healthcheck:
#      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
#      interval: 2s
#      timeout: 3s
#      retries: 40



volumes:
  api-db-data:
    name: api-db-data
  cache:
    driver: local

networks:
  app_network:
    driver: bridge